### ISSUE TITLE
Add constants to package

### ISSUE THREAD

**Issue by sapkra** [milesj/interweave#105]
For my custom matcher I've imported your constants like `URL_PATTERN` so that my matchers will not have any conflict with yours. But since the new version you're not providing them in the published package anymore.

Previous code:
```typescript
import { URL_PATTERN } from 'interweave-autolink/lib/constants';
```

Additionally vs-code is not throwing any errors because the definition file is in the package without the actual related code file.

**Comment by milesj** [comment]
Fair enough request! Will be available in the next patch.
