### ISSUE TITLE
Move doMatch helper out of class

### ISSUE THREAD

**Issue by sapkra** [milesj/interweave#106]
To use the `doMatch` helper function by using an object based matcher it should be outside the Matcher class and become exported.

e.g.

```typescript
import { MatcherInterface, doMatch } from 'interweave';

export const markdownBoldMatcher: MatcherInterface<any> = {
  inverseName: 'noBold',
  propName: 'bold',
  asTag: () => 'b',
  createElement: (children, { key }) => <b key={key}>{children}</b>,
  match: (value: string) => doMatch(value, /\*([^*]+)\*/u, (matches) => ({ match: matches[1] }));,
};
```

**Comment by milesj** [comment]
Sounds good to me. Want to contribute it?

**Comment by sapkra** [comment]
I wanted to contribute it but I don't know how you want to handle the code structure so I created this issue (I didn't know in which file).
Additionally I would mark the old `doMatch` method in the class as deprecated and use in this class the new function. In the next major version this method could be deleted.

**Comment by milesj** [comment]
Good point. I'll dig into this this weekend.

**Comment by milesj** [comment]
Adding a `match` function that you can use for this.
