### ISSUE TITLE
Support for disabling tag / attribute filtering and / or creating custom filter lists

### ISSUE THREAD

**Issue by marcusmateus** [milesj/interweave#11]
Interweave is a solid library that is fairly flexible.  However, we currently use sanitize for filtering tags and attributes with a more permissive list for our use case.  Unfortunately, when we apply interweave currently those more permissive items are removed... we need to either disable filtering in interweave or expand the list to be more permissive.  I was initially thinking disabling would be better, but I do like the performance benefits of doing both filtering and autolinking in a single pass.

I am happy to implement the feature, but want to be sure to do it in a way that is helpful to the library and likely to be merged back in.  Do you have any thoughts or suggestions on how to best approach the problem?

Thanks

**Comment by milesj** [comment]
What kind of tags/attributes are you looking to allow? Everything that is currently in the blacklist falls into one of these categories:

* Outdated/deprecated
* Interactive (like forms)
* XSS/injection vulnerability

I've yet to hear a good reason as to allow any tag/attribute that falls into one of those categories, as the major incentive in using Interweave would be to render markdown/bbcode HTML-like strings in a safe manner.

**Comment by marcusmateus** [comment]
So our use case may not be well aligned with the purpose of Interweave then.  Basically we are trying to safely allow user generated html to be rendered along with certain enhancements like auto-linking and emoji, which Interweave provides.

The tags and attributes I am currently looking to allow through are all related to styling (style tag / attribute and potentially some outdated things like bgcolor, etc.).  Someday that list could expand to include interactive elements, but not now.

**Comment by milesj** [comment]
So the `style` attribute is one I go back and forth one, but currently lean to not supporting, as I would have to filter all the style property values (like background src, etc).

As for the other attributes, yeah, those I don't play to ever support. However, this might be a good use case for a new prop like `noWhitelist`, or something along those lines, which would require the consumer to handle that logic. I'll think about this.

**Comment by milesj** [comment]
@marcusmateus I've been working on a `disableWhitelist` prop. You can view the most recent commits to see it's usage.

**Comment by marcusmateus** [comment]
@milesj, thanks for the work on the `disableWhitelist` prop.  The inclusion of the `style` tag in the `blacklist` means I will still need to maintain a fork to disable that flag for our purposes, but it will at least be even easier now.

Thanks!

**Comment by milesj** [comment]
@marcusmateus What is your use-case for allowing a `<style>` tag? Is this an entire HTML document or something?

**Comment by marcusmateus** [comment]
@milesj, Essentially yes, we are frequently rendering html emails from outside systems.

**Comment by milesj** [comment]
@marcusmateus So what exactly are you using Interweave for? Your use-case seems to infer the complete opposite.

**Comment by marcusmateus** [comment]
@milesj, I'm using it to render email addresses, urls, emojis, etc. that aren't already properly marked up.

**Comment by milesj** [comment]
@marcusmateus Yeah, I'd suggest forking. That is definitely not something Interweave is meant to or will support. I'm even planning to remove entire document parsing from the library.

**Comment by marcusmateus** [comment]
@milesj, thanks for entertaining the discussion.  I will fork.

**Comment by milesj** [comment]
No problem. Thanks for the conversation!
