### ISSUE TITLE
Add support for Fragments

### ISSUE THREAD

**Issue by iepoch** [milesj/interweave#110]
I checked the docs and it doesn't say you don't have support for fragment tags and it doesn't state that you do have support for them. But I just started using interweave I like it but I noticed that.  My data can can also send <fragment> tag but interweave is not displaying it. It does display all other HTML tags just not fragments. Is that a known issue or this is not supported yet?

**Comment by milesj** [comment]
@iepoch You can wrap your content in a fragment by using `tagName="fragment"`. Does that work?

Otherwise a code example would be nice.

**Comment by iepoch** [comment]
Just a little background: I was using Ghost to try and work with Reactjs (I know insane). Anyway their API sends this type of info through the API `<figure class=\"kg-card kg-embed-card\"><iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/qS7zIy9l-Xc?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></figure>`

But I end up with this when I get it on react. 
`<figure class="kg-card kg-embed-card"><iframe widt…re-in-picture" allowfullscreen></iframe></figure>` 
Now both fragment and figure both don't work. I don't like this method and wished Ghost wouldn't send it as html formatted but this is what it gives me.  Really both of them are iframes so I don't understand why it sends it as the figure or fragments. 

You can say I'm new with being a developer I have maybe a year under my belt. So I may not understand this method. But I am thankful you have made this tool.

**Comment by milesj** [comment]
Does it actually look like this `<iframe widt…re-in-picture" allowfullscreen>` or did you do that?

**Comment by iepoch** [comment]
No it actually look like this. 
Console:
![image](https://user-images.githubusercontent.com/7504929/74060796-f19a2a80-49a7-11ea-88c1-751fb9d6fba3.png)

Postman:
![image](https://user-images.githubusercontent.com/7504929/74060872-1c847e80-49a8-11ea-81ef-d1e01c282a99.png)

This is exactly what Ghost will send me through the API. Looking deeper in your documentation I could filter through them and use your LinkFilter component and filter each one it uses. I just didn't know I could but I was hoping it was just add it and it get all the different tags. Sorry for my bad assumptions. However that's what I might have to do and hope that it works.

**Comment by iepoch** [comment]
> Does it actually look like this `<iframe widt…re-in-picture" allowfullscreen>` or did you do that?
Sorry to answer this I did not add ... inside the width that just the way it gets returned through the console.

**Comment by milesj** [comment]
So the `…` is something that the console log is doing.

So what exactly is the issue when loading the page? Does the iframe not work? What does it look like when you inspect the element directly in the console?

**Comment by iepoch** [comment]
Correct it shows nothing on page. It tries to show up it will flash for a moment then show a blank space where the iframe should be.

**Comment by iepoch** [comment]
![image](https://user-images.githubusercontent.com/7504929/74073716-8a40a280-49c8-11ea-8a99-d7b38d1a99a6.png)
Here is a picture to better show it. Thanks Miles.

**Comment by milesj** [comment]
Alright that makes more sense. So `iframe`s are not allowed by default for security reasons. You need to manually allow it.

```ts
import Interweave, { ALLOWED_TAG_LIST } from 'interweave';

<Interweave allowList={ALLOWED_TAG_LIST.concat('iframe')} />
```

**Comment by iepoch** [comment]
Ok that makes sense I was reading through the docs but I didn't understand this 100% . Thank you for getting back me so fast.
