### ISSUE TITLE
Url fragments are not fully identified if they end with special characters

### ISSUE THREAD

**Issue by sapkra** [milesj/interweave#120]
A user tried to use a URL which fragment is ending with a `_` but this sign is not indentified as part of the URL because the `URL_FRAGMENT` pattern is just looking for numbers and letters at the end.

```
https://example.com/#thisismyfragment_
```

**Comment by milesj** [comment]
There's a note about this in the docs: https://milesj.gitbook.io/interweave/extensions/autolink

Fragments must end in alphanumeric characters.

**Comment by milesj** [comment]
Decided to change this. Available in next version.

**Comment by vsvamsi1** [comment]
Hi @milesj, 
Has this issue been fixed? I have installed the latest versions of interweave and interweave-autolink
`
    "interweave": "^13.0.0",
    "interweave-autolink": "5.1.0",
` 
I suspect the issue is with the UrlMatcher Interweave-autolink because the match seems to excluded the underscore.
```
const inst = new UrlMatcher("url");
const inp = "https://something.com/abcfe_";
const result = inst.match(inp);
console.log("see result ", inp, result);
//result.match = "https://something.com/abcfe"
```

**Comment by raushan3737** [comment]
Hi @milesj , Is there any update regarding this issue.
Still i am not able to use `_` at the end. I am using the latest version: 

```
 "interweave": "^13.1.0",
 "interweave-autolink": "^5.1.1"
```
Please update on this if any, Thank you.
