### ISSUE TITLE
HashtagMatcher is detecting fragments in URLs

### ISSUE THREAD

**Issue by sapkra** [milesj/interweave#121]
If you have a URL fragment in the URL the hashtag matcher will detect url fragments as hashtags which I think is a wrong behavior.

```
https://example.com/#thisismyfragment
```

To fix it the hashtag pattern should check for a space or the beginning of the line before the `#`.

Additionally it has the same problem I've mentioned here: #120 
So if the hashtag ends with a special character it is not fully connected. To fix this the regex could check for the end of the line or a space behind the match.

**Comment by milesj** [comment]
Looked into this and it's not an easy fix. Theres so many situations in which hashtags can be used without leading/trailing whitespace or boundaries. For example, wrapped in parens, or brackets, or even stuff like `#foo/#bar` should match both. Checking for leading slash isn't always accurate.

Possible solution is running url matcher first.

**Comment by milesj** [comment]
Going to close this as there's no direct path forward.
