### ISSUE TITLE
Apply onClick event on populated HTML

### ISSUE THREAD

**Issue by sourabh1007** [milesj/interweave#122]
I have a HTML string, which is an unordered list, If I want to add an event on that list HTML. How can I add it? is it possible using this library?

Just to make it clear:

HTML  content =` "<ul><li>a</li> <li>b</li></ul>"`

How can I add onclick event on this list?

HTML  content = `"<ul><li onClick={this.copyToTextbox}>a</li> <li onClick={this.copyToTextbox}>b</li></ul>"`

**Comment by milesj** [comment]
@sourabh1007 No, events are not supported. That's just a giant XSS vulnerability.
