### ISSUE TITLE
Allow customization of banned tags?

### ISSUE THREAD

**Issue by tyteen4a03** [milesj/interweave#123]
How do I allow tags in the banned list through? I have `<iframe>`s and `<script>`s that I need to allow through unchanged.

(Yes, I know where my HTML comes from. Yes, I know this goes against the package's intentions but this is the only React HTML Parser that works in SSR.)

**Comment by milesj** [comment]
Sorry, you can't change the banned list. What is your use case?

**Comment by tyteen4a03** [comment]
This is the only HTML parser I know that works with Next.JS SSR and I would like more freedom over what tags are rendered or not (e.g. <script>)

**Comment by milesj** [comment]
@tyteen4a03 Interweave is meant to sanitize user input that contains HTML, which should most likely not contain `<script>`. If you have full control of the content, especially for SSR, what're you using Interweave for exactly?

**Comment by tyteen4a03** [comment]
As I said, this is the only HTML parser I know that works with Next.JS SSR.

**Comment by tyteen4a03** [comment]
Displaying a legacy application's flat-file databases of custom HTML. I'm really just using Interweave to parse the HTML tags into React components and don't use any sort of filtering / blocking.

**Comment by milesj** [comment]
@tyteen4a03 And I'm guessing `dangerouslySetInnerHTML` is... dangerous?

**Comment by tyteen4a03** [comment]
Which requires a wrapper (you probably know about https://github.com/reactjs/rfcs/pull/129). As I said I only know of this project which works with Next.JS SSR.

**Comment by milesj** [comment]
I don't feel comfortable adding it to the interweave API, as people would just use it as an escape hatch and make things unsafe. 

However, one thing you could do is extend the `Parser` and override the banned logic (https://github.com/milesj/interweave/blob/master/packages/core/src/Parser.ts#L84). Once parsed, pass the nodes to `parsedContent` (https://github.com/milesj/interweave/blob/master/packages/core/src/Markup.tsx#L9). A bit of overhead, but should work.
