### ISSUE TITLE
HTML documents as Interweave content are not supported

### ISSUE THREAD

**Issue by ndanvers** [milesj/interweave#124]
Hello and good day!

Don't mean to bother however I couldn't find information related to the topic, and from the documentation you've kindly posted I do believe I should be able to accomplish what I'm attempting.

**My goal**
  Display HTML containing handlebars in a React project.

**My attempts**
    What works : 

``` 
let test = "<div>{{header.headline}}</div>"
const template = Handlebars.compile(test);
...
return ( <Interweave content=template(...) /> )
```

Using any variation of quote, double quotes, string literals, I'm able successfully populate the page with my desired results. However, if I attempt to bring in the HTML from another source (passed state for instance) I receive the error noted in the title.

**example:**
What doesn't work:
```
//props.location.state.html is === '<div>{{content}}</div>'   
const template = Handlebars.compile(props.location.state.html)
...
return ( <Interweave content=template(...) /> )
```
This crashes with the error "HTML documents as Interweave content are not supported"
From what I can see, the data types are identical, both passing type as strings. 
The only difference I can see operationally is the origin.

Thank you kindly for any info, I was not able to find anything related to this.

**Comment by milesj** [comment]
@ndanvers That error is thrown when the HTML contains `<DOCTYPE />` or `html/body/head` tags. https://github.com/milesj/interweave/blob/master/packages/core/src/Parser.ts#L34

If is a full document, pass `document.body`.

**Comment by ndanvers** [comment]
That certainly explains it, I greatly appreciate the information!

**Comment by WeebNetsu** [comment]
If in React, you can simply do this to remove everything except the body tags:
```
const bodyRegex = /<body[^>]*>([\s\S]*)<\/body>/gi;
const bodyMatches = bodyRegex.exec(html);
const bodyContent = bodyMatches ? bodyMatches[1] : '';
```
