### ISSUE TITLE
Request: TeleMatcher ext. that to match phone numbers and link it using a "tel:" target.

### ISSUE THREAD

**Issue by siwalikm** [milesj/interweave#132]
@milesj Firstly thanks for this great project! I've been exploring it since yesterday and so far loved it.

I think a TeleMatcher extension would be a great addition to this project which matches for telephone numbers and adds a tel: target to them. As telephone links are the most popular link types after URL and Email I think it would be great to have it as an Autolink extension.

If you think this makes sense, we can discuss this further and I can come up with a PR for this.

**Comment by milesj** [comment]
This is something I've wanted to do, but since theres so many different patterns for telephone numbers, I never implemented it. Ideally it would only match based on the user's locale.

**Comment by siwalikm** [comment]
Yes, phone number detection feels really complicated but there are some great libraries which makes life easy.  https://github.com/google/libphonenumber is so far the best library i found for parsing phone numbers.

There's a[ javascript ported version](https://gitlab.com/catamphetamine/libphonenumber-js) of it which pretty accurately detects phonenumbers in a strings and returns it's index values. I was thinking to use lib instead for the detection part.

Here's a [demo](https://runkit.com/o-oo--ooo-oo-o-oo-oo-oooo----oo-o/telematcher) using libphonenumber-js which matches for numbers in any country code. If this looks fine i can give it a go.

**Comment by milesj** [comment]
That library is massive so would need to be an `optionalPeerDependency`, but not opposed to it.

**Comment by milesj** [comment]
This can be done is a third-party plugin, closing.
