### ISSUE TITLE
interweave-autolink EmailMatcher not recognising valid emails with dot in them

### ISSUE THREAD

**Issue by siwalikm** [milesj/interweave#134]
I'm using EmailMatcher from the Autolinking extention and it is not recognising any valid emails which has a dot in it.

Eg.
![image](https://user-images.githubusercontent.com/20061595/96126045-a1e60880-0f11-11eb-8867-07ffe3071c10.png)

[codesandbox link](https://codesandbox.io/s/interweave-auto-link-email-issue-6o89u?file=/src/App.js:96-108)

Edit: this happens specifically when the no. of chars. after the dot is less than 3.

**Comment by milesj** [comment]
Looks like this needs to be tweaked: https://github.com/milesj/interweave/blob/master/packages/autolink/src/constants.ts#L160

It requires 3 characters since the trailing/leading chars have to be alphanumeric.

**Comment by milesj** [comment]
Fixed in latest version.
