### ISSUE TITLE
interweave-autolink UrlMatcher recognising emails as URL

### ISSUE THREAD

**Issue by siwalikm** [milesj/interweave#135]
I'm using UrlMatcher from the Autolinking extention and the extension is detecting an email id as website URL and on click takes to the TLD URL.

Eg.
![image](https://user-images.githubusercontent.com/20061595/96249658-28aaec00-0fcb-11eb-8972-433d8c4a8e81.png)

[codesandbox link](https://codesandbox.io/s/interweave-auto-link-url-issue-uvw5s?file=/src/App.js)

**Comment by milesj** [comment]
Technically this is valid since `user.1@` is the "auth" part of the URL: https://github.com/milesj/interweave/blob/master/packages/autolink/src/constants.ts#L36 We don't require the existence of `http://` so that URLs that look like "google.com" still autolink.

I'm not sure there is a fix here.

**Comment by milesj** [comment]
@siwalikm Sorry its been a while, but was testing this, and I already mark the match as invalid if it looks like an email: https://github.com/milesj/interweave/blob/master/packages/autolink/src/UrlMatcher.ts#L39

Do you happen to have the full test case?
