### ISSUE TITLE
interweave-emoji - Cannot read property 'map' of undefined at EmojiDataManager.packageEmoji

### ISSUE THREAD

**Issue by KmaCoder** [milesj/interweave#139]
Hi! I'm trying to use EmojiMatcher, but it doesn't seem to work. First of all, documentation is not really clear, there are no full working examples and required props. Providing single `emojiPath='https://github.com/twitter/twemoji/blob/gh-pages/36x36/{{hexcode}}.png'` just like in example throws error "Missing emoji source data. Have you loaded using withEmojiData". 
I've managed to fix this error using `const [emojis, source, manager] = useEmojiData()` hook, however emojis haven't appeared and now in `source` prop I get new error saying:
```
TypeError: Cannot read property 'map' of undefined
    at EmojiDataManager.packageEmoji (http://localhost:3000/static/js/14.chunk.js:1442:45)
    at http://localhost:3000/static/js/14.chunk.js:1481:34
    at Array.forEach (<anonymous>)
    at EmojiDataManager.parseEmojiData (http://localhost:3000/static/js/14.chunk.js:1480:10)
    at http://localhost:3000/static/js/14.chunk.js:1792:14
```

All required packages like Emojibase I've installed

**Comment by KmaCoder** [comment]
At this line: https://github.com/milesj/interweave/blob/a7ecb2200b0e254368aaf102e8082a67da3fb51f/packages/emoji/src/EmojiDataManager.ts#L84

<img width="480" alt="Screenshot 2020-12-05 at 14 54 12" src="https://user-images.githubusercontent.com/31987427/101243533-bffa0900-3709-11eb-80d3-474469e49337.png">

**Comment by milesj** [comment]
@KmaCoder What version of emojibase are you using? Sounds like you are maybe using v5, but interweave only support v4. You should be getting peer warnings if this is true.

**Comment by KmaCoder** [comment]
You are right! Downgrading to emojibase v4 and reinstalling all modules helped, thank you
