### ISSUE TITLE
Support of capital-case tags

### ISSUE THREAD

**Issue by ivan-kleshnin** [milesj/interweave#146]
Capital-case tags (think "serialized" React components) are not parsed correctly.

### Example-1 (HTML markup)

```js
const str = `
<p>
  <a href="/about">about</a>
</p>
`

function transform(node, children) {
  if (node.tagName == "A") {
    console.log(children) // ["about"] -- ok
    return <Link href={node.getAttribute("href")}>{children}</Link>
  }
}

export default function Home() {
  return <Interweave content={str} transform={transform}/>
}
```

^ `children` = `["about"]` fine but then...

### Example-2 (HTML+ markup)

```js
const str = `
<p>
  <Link href="/about">about</Link>
</p>
`

function transform(node, children) {
  if (node.tagName == "LINK") {
    console.log(children) // [] -- why not the same ["about"] ?!?
    return <Link href={node.getAttribute("href")}>{children}</Link>
  }
}
```

Is it some bug or an intentional design limitation? Or maybe I miss something. 

---

P.S docs mention `node.tagName === 'a'` which is incorrect and should be `=== 'A'` for the latest Interweave.

**Comment by milesj** [comment]
Interweave is only meant for parsing HTML, not JSX. This will not be supported.
