### ISSUE TITLE
New in 12.7.0, source maps pointing to missing files

### ISSUE THREAD

**Issue by bravely** [milesj/interweave#149]
```WARNING in ./node_modules/interweave/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/pepyri/workbase/workbase-mono/frontend/node_modules/interweave/src/match.ts' file: Error: ENOENT: no such file or directory, open '/home/pepyri/workbase/workbase-mono/frontend/node_modules/interweave/src/match.ts'
```

We are getting a number of these when using Webpack's source maps feature. It seems to be pointing to files that aren't included in the 12.7.0 build. I'm guessing, based on looking at the difference between the library before and after, that 12.7.0 added source maps to the `esm` build with packemon?

**Comment by milesj** [comment]
This is fixed.
