### ISSUE TITLE
Interweave & Gatsby build

### ISSUE THREAD

**Issue by nerdess** [milesj/interweave#154]
I am currently refactoring some Gatsby code to ditch dangerouslySetInnerHTML in favour of interweave. 

On `gatsby develop` everything works fine, some simple example like `<Interweave content="Hello World" />` works. I get `<span>Hello World</span>` in the browser.

But generating the static HTML with `gatsby build` and then checking the code no "Hello World" is displaying. I only get a lonely empty `<span></span>`.

Any help or hints on where to dig would be great!

**Comment by nerdess** [comment]
ah ok figured out I need to include https://interweave.dev/docs/ssr/ in order to get it to work. all good :)

**Comment by arsinclair** [comment]
To add to this information, when using interweave-ssr with Gatsby the polyfill function needs to be called only once, and a most logical place to put it is _gatsby-ssr.ts_:

```ts
import { polyfill } from "interweave-ssr";

polyfill();
```
