### ISSUE TITLE
Lowercase hexcode for emojiPath

### ISSUE THREAD

**Issue by zehawki** [milesj/interweave#155]
With the default example: 

`content="This will convert emoji unicode characters (🌀), shortcodes (:cyclone:), and emoticons to SVGs! :)"`

Hexcodes are being generated as 1F300, 1F642. However both maxCDN and cloudflare use lowercase, ie 1f300 and 1f642 etc.

Is there a way to ensure lower case hexcodes when creating the path eg 

`emojiPath="https://twemoji.maxcdn.com/v/latest/72x72/{{hexcode}}.png"`

**Comment by milesj** [comment]
@zehawki So you can pass a function to `emojiPath` and format it: https://interweave.dev/docs/exts/emoji#displaying-svgs-or-pngs

**Comment by zehawki** [comment]
Ah yes.

Though I noticed that one does not need to do this at all if using the useEmojiData() hook: https://interweave.dev/docs/exts/emoji/#loading-emoji-data.
