### ISSUE TITLE
Misc queries about interweave-emoji

### ISSUE THREAD

**Issue by zehawki** [milesj/interweave#156]
@milesj as always, thank you for making such high quality libraries available. I have the following queries / bits of confusion:

A. Why do we need this library (interweave-emoji)?

- AFAIK, there is native support in browsers for emojis that are pasted into text fields and even without interweave-emoji, this works fine.
- However if one wants to support shortcode and emoticons, THEN interweave-emoji is needed.

Is this your understanding as well?

B. renderUnicode must always be turned on?

If I keep this off, then I get some strange results like this:

![image](https://user-images.githubusercontent.com/8095144/112140526-209a4c80-8bfa-11eb-85b2-7973bc8c7ecf.png)

with the resultant code:

![image](https://user-images.githubusercontent.com/8095144/112140594-33148600-8bfa-11eb-9509-52ffce49bcd0.png)

Is this expected? and hence should renderUnicode always be true?

**Comment by milesj** [comment]
@zehawki 

A:

You are correct that all platforms support unicode and you may not need this lib, but there's a few reasons why you would convert them to an SVG/image.

- You want consistent emoji designs across all platforms.
- You want to support new emoji that do not exist on the platform yet.

B:

That looks correct. It's converting emoticons/shortcodes to images with the unicode character as `alt` text, but the images are broken so it's showing the alt text.
