### ISSUE TITLE
Global is not defined

### ISSUE THREAD

**Issue by raphael10-collab** [milesj/interweave#161]
In my `Electron-React-Typescript-Webpack` app I'm now trying to use `interweave`in a `tsx` page:

    import Interweave, { Markup } from 'interweave';

    function App_B() {

        return (
          <div id="outer-container" className='outer-container'>

            <div id="my-content" className="plaintext">
              <Interweave content="This string contains <b>HTML</b> and will safely be rendered!" />
            </div>
          </div>
        );
    }

I get this error: `Global is not defined` 

![image](https://user-images.githubusercontent.com/70313067/115427788-115eec80-a202-11eb-8772-14874305a378.png)

How to solve the problem?
Looking forward to your kind help

**Comment by raphael10-collab** [comment]
@milesj I "solved" putting in the `HTML` page linked to the `tsx` page this line:

    <script> const global = globalThis; </script>

Why did this happen with `interweave` and not with other libraries I'm using?

**Comment by milesj** [comment]
@raphael10-collab Interweave access the global for SSR: https://github.com/milesj/interweave/blob/master/packages/core/src/Parser.ts#L271

It's weird you are hitting this and no one else, so I'm assuming it's because of not using Terser, which would minify this away I believe. I can fix it though.

**Comment by milesj** [comment]
Added a fix for this.
