### ISSUE TITLE
Whitespace text nodes cannot appear as  a child of  <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.

### ISSUE THREAD

**Issue by raphael10-collab** [milesj/interweave#162]
In my `Electron-React-Typescript-Webpack` app yesterday I installed and started to use`interweave`, which seems working.
But I get this Warning:

    Whitespace text nodes cannot appear as  a child of  <table>. Make sure you don't have any extra whitespace between tags on   
    each line of your source code.

![image](https://user-images.githubusercontent.com/70313067/115518755-d653cc00-a288-11eb-9462-f56668b9e638.png)

How to solve it?

**Comment by milesj** [comment]
@raphael10-collab There's another thread on this issue here: https://github.com/milesj/interweave/issues/138

The gist is that this error comes from React and Interweave isn't causing it.

**Comment by raphael10-collab** [comment]
Ok Thank you.
