### ISSUE TITLE
Request of Help: how to properly extract the hyperlinks associated to `href` elements?

### ISSUE THREAD

**Issue by raphael10-collab** [milesj/interweave#163]
I'm using this custom component taken from https://interweave.dev/docs/compose

    import React from 'react';
    import BaseInterweave, { InterweaveProps, FilterInterface, MatcherInterface } from 'interweave';
    import { IpMatcher, UrlMatcher, EmailMatcher, HashtagMatcher } from 'interweave-autolink';

    const globalMatchers: MatcherInterface[] = [
      new EmailMatcher('email'),
      new IpMatcher('ip'),
      new UrlMatcher('url'),
      new HashtagMatcher('hashtag'),
    ];

    interface Props extends InterweaveProps {
      instagram?: boolean;
      twitter?: boolean;
    }

    export default function Interweave({
      filters = [],
      matchers = [],
      twitter,
      instagram,
      ...props
    }: Props) {
      let hashtagUrl = '';

      if (twitter) {
        hashtagUrl = 'https://twitter.com/hashtag/{{hashtag}}';
      } else if (instagram) {
        hashtagUrl = 'https://instagram.com/explore/tags/{{hashtag}}';
      }

      return (
        <BaseInterweave
          matchers={[...globalMatchers, ...matchers]}
          hashtagUrl={hashtagUrl}
          newWindow
          {...props}
        />
      );
    }

And in the React page:

    import Interweave from './Interweave';

    function App_B(props) {

        return (
          <div id="outer-container" className='outer-container'>

            <div id="my-content" className="plaintext">
              <Interweave content={text} />
            </div>

          </div>
        );

In order to extract the hyperlinks associated to `href` elements in the `html` page I've added:

    <script>
      const hrefs = document.getElementsByTagName('href');
      for (href in hrefs) {
        console.log("href: ", href, "-> href.attr: ", href.attr);
      }
    </script

But I get 

    index_B.html:28 href:  length -> href.attr:  undefined
    index_B.html:28 href:  item -> href.attr:  undefined
    index_B.html:28 href:  namedItem -> href.attr:  undefined

![image](https://user-images.githubusercontent.com/70313067/115688678-a6c1c400-a35b-11eb-93fa-82ed93b48a4b.png)

**Comment by milesj** [comment]
@raphael10-collab What're you trying to do exactly?

`href` isnt an element, do you want `a` instead? `document.getElementsByTagName('a');`

**Comment by raphael10-collab** [comment]
@milesj Putting 

      const as = document.getElementsByTagName('a');
      for(a in as) {
        console.log("a: ", a);
      }

I get:

    a:  length
    a:  item
    a:  namedItem


![image](https://user-images.githubusercontent.com/70313067/115758590-96333d00-a39f-11eb-95c4-2a13d6da3b0e.png)

**Comment by milesj** [comment]
@raphael10-collab You need to use `for(a of as) {` instead of `for(a in as) {`. You also need to run this script _after_ Interweave has rendered.

**Comment by raphael10-collab** [comment]
Thank you!!!
