### ISSUE TITLE
<Markup> element by default renders as a 'div', instead of 'span'

### ISSUE THREAD

**Issue by arsinclair** [milesj/interweave#164]
From https://interweave.dev/docs/#props:

> Props
> ...
> `tagName` (`string`) - The HTML element tag name to wrap the output with. Defaults to "span".
> ...

This is not true, it defaults to `span` only for Interweave component, but not for Markup.

I am using Markup in such way:

```ts
import { Markup } from "interweave";


<Markup content={"Test string <br/>with a line break."} />
```

It renders as `div`.

Either it is a bug or docs will have to be updated.

**Comment by milesj** [comment]
@arsinclair This would technically be a breaking change, since it would disrupt HTML content flow. So it'll have to wait until the next major. Until then you can use `tagName`.

**Comment by arsinclair** [comment]
@milesj , of course, thank you.

**Comment by milesj** [comment]
Went ahead and updated markup to be span in the next version.
