### ISSUE TITLE
How can I create a custom matcher that replace a <img> tag to a Next.js <Image> component?

### ISSUE THREAD

**Issue by aresrioja10** [milesj/interweave#174]
I would like to transform all the <img> tags from my html content to Next.js <Image> components https://nextjs.org/docs/api-reference/next/image

Is that possible?

I've checked the documentation but I'm not sure to understand how it works.

**Comment by milesj** [comment]
@aresrioja10 You wouldn't use a matcher but a transformer: https://interweave.dev/docs/parser#replacing-elements
