### ISSUE TITLE
Email address fails match if two letter username is used

### ISSUE THREAD

**Issue by michaelkantor** [milesj/interweave#175]
I'm observing that ttt@gmail.com matches correctly, but that tt@gmail.com does not. tt@gmail.com is transformed into `{{{url0}}}tt@gmail.com{{{/url0}}}`.

Digging into the code, I see it enters a state that looks somewhat like: `{{{url0 {email0}}}}tt@gmail.com...` (going from memory here so might not have that exactly right). This state does not come up for ttt@gmail.com.

I may dig into this more later, but suspect it involves editing large regex expressions that may have rationale for being the way they are...

**Comment by milesj** [comment]
Ok I see the problem: https://github.com/milesj/interweave/blob/master/packages/autolink/src/constants.ts#L156

Emails expect the first and last characters to be valid alphanumeric characters, then the middle chars can be anything. This results in a length of 3 required. Can update it to support 2, but not sure if it can support 1 (is that even valid? :P)

**Comment by michaelkantor** [comment]
I think the number of users impacted for having a one letter email address is small enough for us not to need to worry about them? 😆

**Comment by michaelkantor** [comment]
An alternate philosophy to fixing this: don't worry if 1 or even 2 letter email addresses are linkified. But do insure that `{{{url0}}}` is never returned

**Comment by milesj** [comment]
Will be fixed in next version.
