### ISSUE TITLE
How do I change the target attribute to _top or _blank

### ISSUE THREAD

**Issue by edouard-lopez** [milesj/interweave#178]
Hello thanks for the lib, it work nicely.

My link (URL or email) are in a `iframe` app so I need to add a `target=_top`. Do I need to create a custom matcher for both or is there something simpler?

**Comment by edouard-lopez** [comment]
Got something working, but there is a bunch of boilerplate. 

If there is something simpler, I'm open to ssugestions as I also need this for emails :)

### Usage

I use my `CustomUrlMatcher`

```
<Linkify
  content={props.content}
  matchers={[new CustomUrlMatcher('url'), new EmailMatcher('email')]}
>
  {props.children}
</Linkify>
```

### Custom files

./Linkify/
├── CustomLink.tsx
├── CustomUrlMatcher.tsx
└── CustomUrl.tsx


#### CustomLink.tsx

Adding the `target="_top"` attribute.

```
import { LinkProps } from 'interweave-autolink';
import React from 'react';

export default function CustomLink({
  children,
  href,
  onClick,
}: LinkProps): JSX.Element {
  return (
    <a href={href} target="_top" onClick={onClick} rel="noopener noreferrer">
      {children}
    </a>
  );
}
```

#### CustomUrl.tsx

Using my `<CustomLink>` component.

```
import React from 'react';
import { UrlProps } from 'interweave-autolink';
import CustomLink from './CustomLink';

export default function Url({
  children,
  url,
  urlParts,
  ...props
}: UrlProps): JSX.Element {
  let href = url;

  if (!href.match(/^https?:\/\//)) {
    href = `http://${href}`;
  }

  return (
    <CustomLink {...props} href={href}>
      {children}
    </CustomLink>
  );
}
```

#### CustomUrlMatcher.tsx

Invoking my `<CustomUrl>` component to render.

```
import { ChildrenNode, Node } from 'interweave';
import { UrlMatcher, UrlMatcherOptions, UrlProps } from 'interweave-autolink';
import React from 'react';
import CustomUrl from './CustomUrl';

export default class CustomUrlMatcher extends UrlMatcher {
  constructor(
    name: string,
    options?: UrlMatcherOptions,
    factory?: React.ComponentType<UrlProps> | null
  ) {
    super(
      name,
      {
        customTLDs: [],
        validateTLD: true,
        ...options,
      },
      factory
    );
  }

  replaceWith(children: ChildrenNode, props: UrlProps): Node {
    return React.createElement(CustomUrl, props, children);
  }
}
```

**Comment by milesj** [comment]
@edouard-lopez You can just pass a 3rd argument to `UrlMatcher`: https://interweave.dev/docs/matchers#rendered-elements

Or use a transformer to modify the element: https://interweave.dev/docs/parser#replacing-elements

**Comment by edouard-lopez** [comment]
@milesj 

Using the custom renderer with native `UrlMatcher`/`EmailMatcher`, I got my `<CustomLInk>` but `href` has an `undefined` value:

```
<Linkify.Component
          content={props.content}
          matchers={[
            new UrlMatcher('url', {}, Linkify.CustomLink),
            new EmailMatcher('email', {}, Linkify.CustomLink),
          ]}
        >
          {props.children}
        </Linkify.Component>
```

**Comment by milesj** [comment]
@edouard-lopez Are you using TypeScript? If not, the prop passed is `url`, not `href`, so you'll need to map that yourself.

https://github.com/milesj/interweave/blob/master/packages/autolink/src/Url.tsx#L6

**Comment by edouard-lopez** [comment]
My complete implementation

### CustomLink.tsx

```
import { LinkProps } from 'interweave-autolink';
import React from 'react';

export default function CustomLink({
  children,
  href,
  onClick,
}: LinkProps): JSX.Element {
  return (
    <a href={href} target="_top" onClick={onClick} rel="noopener noreferrer">
      {children}
    </a>
  );
}
```

### CustomUrl.tsx

```
import React from 'react';
import { UrlProps } from 'interweave-autolink';
import CustomLink from './CustomLink';

export default function Url({
  children,
  url,
  urlParts,
  ...props
}: UrlProps): JSX.Element {
  let href = url;

  if (!href.match(/^https?:\/\//)) {
    href = `http://${href}`;
  }

  return (
    <CustomLink {...props} href={href}>
      {children}
    </CustomLink>
  );
}
```

### CustomUrlMatcher.tsx

import { ChildrenNode, Node } from 'interweave';
import { UrlMatcher, UrlMatcherOptions, UrlProps } from 'interweave-autolink';
import React from 'react';
import CustomUrl from './CustomUrl';

export default class CustomUrlMatcher extends UrlMatcher {
  constructor(
    name: string,
    options?: UrlMatcherOptions,
    factory?: React.ComponentType<UrlProps> | null
  ) {
    super(
      name,
      {
        customTLDs: [],
        validateTLD: true,
        ...options,
      },
      factory
    );
  }

  replaceWith(children: ChildrenNode, props: UrlProps): Node {
    return React.createElement(CustomUrl, props, children);
  }
}

### Linkify.tsx

```
import Component from 'interweave';
import CustomEmailMatcher from './CustomEmailMatcher';
import CustomUrlMatcher from './CustomUrlMatcher';

export { Component, CustomEmailMatcher, CustomUrlMatcher };
```

### Usage

```
<Linkify.Component
  content={props.content}
  matchers={[
    new Linkify.CustomUrlMatcher('url'),
    new Linkify.CustomEmailMatcher('email'),
  ]}
>
  {props.children}
</Linkify.Component>
```
