### ISSUE TITLE
Provide an example of styled Interweave component

### ISSUE THREAD

**Issue by arsinclair** [milesj/interweave#182]
Hello there,

First of all, thank you so much for this awesome plugin.

I'm using it on a Gatsby site, and with most of my components I'm applying a [styled-components](https://styled-components.com) approach. However I wasn't able to figure out how to make it work with Interweave. **Could you provide an example?**

---

I think it happens because Interweave by default strips off all attributes, including `className`, and `styled` library actually passes down a random class name every run, so it is just never applied. I know that Interweave can accept a class name prop inside of attributes object, however there's probably no way to make _styled_ to pass it down this way.

Currently I am using css modules as a workaround, so I import the css, get the class names, and then pass it down to Interweave. But this is really inconvenient, and I would love to be able to only use styled components.

**Comment by milesj** [comment]
@arsinclair So Interweave was mainly designed to run and return text only, and I've really never thought about styling it before. Do you have an example of the styles you want to apply?

With that being said, in the next major, this will most likely return fragments and no actual DOM element.

**Comment by arsinclair** [comment]
# Use Cases

Usually I do something like this:

```js
const StyledParagraph = styled.p`
    color: red;
    font-size: 20px;
`;

// Then later on when it renders, I use it like this:

<StyledParagraph>sample text</StyledParagraph>
```

Now there's a need to render arbitrary text in the StyledParagraph. The string that is passed to StyledParagraph will contain an anchor tag, so here the need for Interweave comes in. Below are the approaches I tried.

## Method 1 - Styling the Interweave component itself (doesn't work)

```js
// definition
const StyledParagraph = styled(Interweave)`
    color: red;
    font-size: 20px;
`;

// usage
const sampleTextWithLink = "sample text; <a href='#'>sample link</a>";

<StyledParagraph tagName="p">{sampleTextWithLink}</StyledParagraph>
```

## Method 2 - Using CSS or CSS-modules (works as a workaround, but undesirable, as can't use all the benefits of styled components)

`myComponent.module.css`

```css
.redParagraph {
    color: red;
    font-size: 20px;
}
```

`myComponent.tsx`
```js
import * as styles from "./myComponent.module.css";

// usage
<Interweave 
    tagName="p"
    attributes={{ className: styles.redParagraph }}
    content={sampleTextWithLink}
/>
```

### Method 3 - Wrap styled component around Interweave component (doesn't always work as not all CSS styles are inherited in the same way; bloats the code with unnecessary html tags)

```js
// definition
const StyledParagraph = styled.p`
    color: red;
    font-size: 20px;
`;

// usage
const sampleTextWithLink = "sample text; <a href='#'>sample link</a>";

<StyledParagraph><Interweave content={sampleTextWithLink} /></StyledParagraph>
```

This method will produce something like this:

```
<p class="sc-14tc3tw-9 jYPwFq">
    <span>sample text; <a href="#">sample link</a></span>
</p>
```
There's an unnecessary \<span\> tag which doesn't fulfil any purpose.

---

> Interweave was mainly designed to run and return text only

But it doesn't return text. At least at the moment of writing this.

> in the next major, this will most likely return fragments and no actual DOM element

I would have to test it before saying anything, but I think this way it'll be able to solve the problem.

**Comment by milesj** [comment]
Ok makes sense. I'll add a `className` prop to support this.

**Comment by arsinclair** [comment]
> I'll add a className prop to support this

That's probably going to fix it. Don't know what was the reason behind removed _className_, so I didn't consider it as option.

**Comment by milesj** [comment]
Is added in next version.
