### ISSUE TITLE
Add Mentions Matcher

### ISSUE THREAD

**Issue by harpreet9629** [milesj/interweave#186]
Hi,

Can you please add Mention Match also?

**Comment by OmkarK45** [comment]
I wrote a custom matcher for mentions. You can find it here https://github.com/milesj/interweave/issues/196

The typescript types are any as of now. I'll come up with better types

**Comment by ci7lus** [comment]
@milesj May I submit a PR to add MentionMatcher to this repository? Because I feel that it would be more cohesive if it were in an autolink package.

**Comment by milesj** [comment]
Sure, feel free.
