### ISSUE TITLE
URL matcher - selectively new window or not based on link

### ISSUE THREAD

**Issue by BruceWheaton** [milesj/interweave#193]
Big interweave fan. Is there a way to open certain links (same host, and/or hashtags) with a new tab, and some without?

Do I need to make a custom matcher that grabs URLs before the built-in Url matcher and looks for the correct host or even a missing host?

**Comment by milesj** [comment]
Not positive off the top of my head, but you can maybe use a transformer and modify the element being passed in: https://interweave.dev/docs/parser#replacing-elements

**Comment by milesj** [comment]
I'm gonna make this easier in the next rewrite.
