### ISSUE TITLE
Need help with CustomMatcher

### ISSUE THREAD

**Issue by OmkarK45** [milesj/interweave#196]
Thank you for creating this awesome library. I'm writing a matcher to for '@' mentions in a string. 
So far I have managed to work it till here

```
import { Matcher, MatchResponse } from 'interweave'
import { Link } from 'next/link'
import React from 'react'

// Regex to detect @ mentions 
export const MENTION_PATTERN = /^@?(\w){1,15}$/

// render a nextjs link pointing to user's profile 
export function Mention({ handle, ...props }: any) {
	console.log(props)
	return <Link href={`/profile/${props.display}`}>{props.display}</Link>
}

export class MentionMatcher extends Matcher {
	replaceWith(match: string, props) {
		return React.createElement(Mention, props, match)
	}

	asTag(): string {
		return 'a'
	}

	match(string: string): MatchResponse<{
		display: string
		
	}> | null {
		return this.doMatch(string, MENTION_PATTERN, (matches) => {
			return {
				display: matches[0]
			}
		})
	}
}
```

```
<Interweave 
	matchers={[new MentionsMatcher('mention')]} 
	handle={handle=> `/profile/${handle}`}
/>
```

However, this is only detecting if the string contains only "@some_username"

This works [correctly autolinked] -> "@some_username"
This does not [@ mention is rendered as plain string] -> "Had dinner with @some_username"

Is there something I'm missing?

Following pattern is being printed for a string that has "#OK @person_username" {{{hashtag0}}}#OK{{{/hashtag0}}} @person_username

**Comment by OmkarK45** [comment]
Update : Turns out the regex I was using wasn't detecting all the @ signs 
Here's what I ended up using  /\B@(\w+)/
Just replace the MENTIONS_REGEX to  /\B@(\w+)/

**Comment by milesj** [comment]
Glad you got it working!
