### ISSUE TITLE
Hashtags matcher classname

### ISSUE THREAD

**Issue by zehawki** [milesj/interweave#202]
Hi @milesj, is it possible to control the classname of the anchor link that is generated when the `HashtagMatcher` matches something.

I can of course do this in the transform function, but (please correct me if I'm wrong) I see that if the `HashtagMatcher` runs it does not subsequently call the transform function.

**Comment by milesj** [comment]
@zehawki You'd have to replace the component being rendered entirely. https://interweave.dev/docs/matchers#rendered-elements
