### ISSUE TITLE
When render content with same value, behavior is not stable

### ISSUE THREAD

**Issue by Snowing222** [milesj/interweave#209]
I want to render an image. When I uploaded another image to the same url, the behavior is not stable. Sometimes, it render the old image, sometimes it render the new image. 
interweave(content=`<img src="${filePath.path}" />`)

**Comment by milesj** [comment]
@Snowing222 There's not much in Interweave I can do about this. If the URLs are the same, then the browser is caching it. You need to change the file paths and make them unique.
