### ISSUE TITLE
Rel attribute is stripped from a tags

### ISSUE THREAD

**Issue by Mojova** [milesj/interweave#210]
I have text content with `a` elements that have `target="_blank"`. I want them to also have `rel="noopener noreferrer"`, but Interweave strips that tag by default. [Here’s a CodeSandox that demonstrates the issue](https://codesandbox.io/s/interweave-rel-issue-e2905). The Google link should have a rel attribute, but it doesn’t.

**Comment by milesj** [comment]
Will be fixed in next version.
