### ISSUE TITLE
`.app` domain is not supported

### ISSUE THREAD

**Issue by bigint** [milesj/interweave#229]
`.app` domain is not supported

<img width="235" alt="Screenshot 2022-05-28 at 1 17 03 AM" src="https://user-images.githubusercontent.com/69431456/170780047-c5795825-1dc1-4c3b-9ca5-fe82a4f27dfe.png">

**Comment by bigint** [comment]
cc @milesj

**Comment by bigint** [comment]
Same `.xyz` is not supported 😭

**Comment by milesj** [comment]
@bigint You can add your own custom domains: https://interweave.dev/docs/exts/autolink#tld-support
