### ISSUE TITLE
URL parsing fails on Facebook links

### ISSUE THREAD

**Issue by mvolk** [milesj/interweave#23]
Facebook links with the form `https://www.facebook.com/abcde.fge.3?ref=br_rs` are not correctly parsed. `https://www.facebook.com/abcde.fge` is treated as a hyperlink, and the remaining `.3?ref=br_rs` is treated as plain text trailing the hyperlink.

**Comment by kesne** [comment]
Looks like this is happening because dots are being explicitly disallowed in the `URL_CHAR_PART` here: https://github.com/milesj/interweave/blob/c06c7c1d16913f49c9e60ce0e522e3ed7b908fd2/packages/interweave-autolink/src/constants.js#L18

**Comment by milesj** [comment]
This is intended because I don't know whether the period is part of the URL or the end of a sentence. I haven't had the time to dig into it any further.

**Comment by kesne** [comment]
Maybe we could disallow periods followed by spaces, but not periods by themselves?

**Comment by milesj** [comment]
You can't expect uses to type grammar correctly or this to work correctly in other languages.

**Comment by milesj** [comment]
@mvolk @kesne Believe I got this working.
