### ISSUE TITLE
<meta not rendering at all

### ISSUE THREAD

**Issue by cheddar123** [milesj/interweave#233]
Hello,

I am trying to insert meta tags from a cms, (use case is adding 3rd party site authentication to site).

So I created a meta tag `<meta name="cms_test" content="This is a test" />` and it does not seem to render.

Any ideas?

-John

**Comment by milesj** [comment]
@cheddar123 Meta tags are not supported. Only tags within `body` are.

**Comment by cheddar123** [comment]
Thanks for the quick reply.  And good to know.  I was able to solve the problem by using `html-react-parser` for this use case.
