### ISSUE TITLE
ID attribute is not working

### ISSUE THREAD

**Issue by armagananteplioglu** [milesj/interweave#257]
Hello, thank you for this package. Id attribute doesn't get added in the HTML produced by Interweave. Code below (the top line on the screenshot) doesn't work:

`<Interweave content={"Hello World"} id={"myId"} />`

It should work same as the code below (bottom line on the screenshot):

`<span id={"myId"}>Hello World</span>`

![image](https://github.com/milesj/interweave/assets/71595820/6077910d-bf52-40f8-a48c-28ab553feb16)

**Comment by milesj** [comment]
@armagananteplioglu Pretty sure it needs to be: `<Interweave content={"Hello World"} attributes={{id: "myId"}} />`

**Comment by armagananteplioglu** [comment]
Yes that worked, thank you very much!

**Comment by arsinclair** [comment]
@milesj it seems `attributes` is not documented anywhere, or I'm just looking in a wrong place?

**Comment by arsinclair** [comment]
That's unfortunate. Is there an intention to maintain the docs, if so, are the PRs welcomed?

**Comment by arsinclair** [comment]
Done #258
