### ISSUE TITLE
Add Tailwind classes in my html content

### ISSUE THREAD

**Issue by harshalone** [milesj/interweave#261]
Hi I am rendering my html 

```
<Interweave 
                        content={post ? post.content : "" } 
                        matchers={['<p>', '<p className="text-3xl">']}
 /> 
```

But it is throwing error. What I want is simply add a class whenever there is a <p> tag. 

How do I create this matcher and include into my nextjs app? 

The documentation here does not explain it very well.

Should I create a file called myMatcher.js and include it into my component and then it will do the matching? how does it work? can you please explain with an example.

**Comment by milesj** [comment]
@harshalone Matches are class instances that replace content with regex, it's not an array of HTML tags.

Use a transformer instead: https://interweave.dev/docs/parser#replacing-elements
