### ISSUE TITLE
Allow using Fragment for tagName

### ISSUE THREAD

**Issue by rmccue** [milesj/interweave#30]
It would be great if the top-level Element could be any React component rather than specifically just a DOM string. In particular, it'd be nice to be able to use `React.Fragment` in order to avoid having any wrapper at all with React 16.2+.

**Comment by rmccue** [comment]
(This is actually already possible by just passing it in, but you get warnings about the `className` prop being passed to `React.Fragment`, and the propType check fails. As a side note, it would be great to not have `interweave` classes added to anything.)

**Comment by milesj** [comment]
I'm cool with this. I can tackle it sometime this week.

**Comment by rmccue** [comment]
@milesj Did you ever get a chance for this, or should I send a PR?

**Comment by milesj** [comment]
Was going to look into it after your PR lands.

**Comment by milesj** [comment]
Can pass "fragment" now to `tagName`.

**Comment by rmccue** [comment]
Brilliant, thanks!
