### ISSUE TITLE
srcset not supported attribute on img

### ISSUE THREAD

**Issue by rmccue** [milesj/interweave#49]
`img` supports `src`, but not `srcset` or `sizes`. This means that we're not able to progressively load image sizes, and can lead to inconsistency with using Interweave as a replacement for regular HTML parsing.

For example:
```
<img
    src="//placehold.it/300x147"
    srcset="//placehold.it/1024x501 1024w"
    sizes="(max-width: 1099px) 100vw, 1099px"
    width="1099"
    height="539"
/>
```

Expected: see "1024 x 501" image.
Actual: see "300 x 147" image.

**Comment by rmccue** [comment]
It would actually be really handy to be able to specify `TAGS` and `ATTRIBUTES` manually; we're using WordPress as a backend, so I'd like to be able to have Interweave exactly in sync with that.

**Comment by milesj** [comment]
Updated to support both of those. I'm against making the maps configurable as this library has been penetration tested and built to cover most XSS injection/cases. If you feel like something should be added, feel free to submit another PR.
