### ISSUE TITLE
Dealing with blacklisted tags

### ISSUE THREAD

**Issue by rmccue** [milesj/interweave#50]
I have some content which has embedded media in it. These embeds almost entirely use blacklisted elements, typically `iframe`.

I don't expect Interweave to handle these, but I'd like to be able to build in custom functionality on this, so that we can whitelist specific embeds from external sources, and embed these ourselves with custom React elements.

For example, a Spotify embed:
```
<iframe src="https://open.spotify.com/embed/track/6wg8nDWs3MAUEYEd8tO6Hf" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```

We can match this to a `SpotifyEmbed` component, except that there's no way of disabling the blacklist, or handling these in `transform`.

Not sure what the best solution to this should be, but interested in discussing possible paths towards sorting this out.

Sidenote: Some embeds (e.g. Twitter) use a HTML element + script tag. These can be sorted nicely with a `transform` already, because we can match the HTML element. We can also manage this with a [custom container wrapper](https://github.com/humanmade/react-oembed-container).

**Comment by rmccue** [comment]
I'm wondering if we could have something like a `transformBlacklisted` function that receives only [blacklisted tags](https://github.com/milesj/interweave/blob/78f2fd904de003574a5151e19ef8c231774a3f4d/packages/core/src/Parser.ts#L403-L406), and must return a custom React element (or non-blacklisted node).

**Comment by milesj** [comment]
Can probably update transform to accept blacklisted. Let me think about this.

**Comment by milesj** [comment]
Updated the `transform` callback to handle blacklisted. You should be able to intercept now.

**Comment by rmccue** [comment]
Brilliant, thanks.
