### ISSUE TITLE
Valid boolean attributes are stripped

### ISSUE THREAD

**Issue by rmccue** [milesj/interweave#52]
I have HTML content which looks like:

```html
<video controls muted src="http://example.com">
```

Interweave treats these attributes as `false` when [casting to boolean](https://github.com/milesj/interweave/blob/19579435673781000615f704e68107fbde132847/packages/core/src/Parser.ts#L314-L315). It also treats `"true"` as truthy.

Per the [HTML specification](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes):

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.
> Note: The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

**Comment by rmccue** [comment]
I clarified this one [on Twitter](https://twitter.com/gsnedders/status/1072235605927608321):
> That's is the right bit of the spec for this: it's present, therefore it's true. The following sentence is essentially an authoring conformance requirement, and doesn't in any way override this.

Therefore, we should set the value to `true` if it's set at all.

**Comment by milesj** [comment]
@rmccue I disagree. That may be what the spec says, but I'd wager many developers have passed `="false"` or something similar in their HTML. We should probably just remove them if that happens.

**Comment by rmccue** [comment]
Developers may do that, but it won't work, as browser behaviour matches the spec: https://codepen.io/anon/pen/GPgQNK

Firefox, Chrome, and Safari all treat the presence of a boolean attribute as truthy, even if the value is empty string, `"false"`, `"0"`, etc. Interweave should match this behaviour so that it can match `dangerouslySetInnerHTML`'s behaviour.

**Comment by milesj** [comment]
Hrmmm, not sure I fully agree with the change though. This would definitely be a breaking change, so I'd wait till my TS PR is done before handling this.

**Comment by rmccue** [comment]
In the meantime, would you consider merging a change to allow at least empty string to be treated as true? This is breaking our parsing right now.

**Comment by milesj** [comment]
@rmccue Yeah that'll be fine.
