### ISSUE TITLE
Why do many libraries for xss have no blacklist ？

### ISSUE THREAD

**Issue by 951565664** [milesj/interweave#57]
Why do many libraries for xss have no blacklist ？

**Comment by milesj** [comment]
I'm not sure I follow. Interweave does have a blacklist if that's what you're asking. https://github.com/milesj/interweave/blob/master/packages/core/src/constants.ts#L260

It also has a whitelist.

**Comment by 951565664** [comment]
I didn't express clearly. What I actually mean is that users can set a blacklist.But this seems to be an unsafe way.

**Comment by 951565664** [comment]
You seem to be correct, let me think about it, thank you very much.
