### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by zehawki** [milesj/interweave#59]
Hello, the documentation provided is comprehensive, but quite dry. This is a fantastic library, but its difficult to use until you give people a jump start with examples of actual code snippets and how to use.

Couple of month ago, I could not figure out how to actually use it to render HTML, nothing in the doc gave even a simple example. Finally I found just one example on this thread https://stackoverflow.com/a/47159227 and used it successfully. The Markup component is not even mentioned in your documentation.

Now I wanted to use autolinking for URLs. Again there are no examples of how one can actually accomplish this. I had to hack it together by reading https://milesj.gitbook.io/interweave/extensions/autolink and https://github.com/milesj/interweave/blob/master/tests/bundle.tsx and https://github.com/humanmade/interweave.

Thanks.

**Comment by milesj** [comment]
@zehawki Good call out! I actually have a to do on my list to provide more examples. 

I'm not sure what they would really look like outside of something like this, `<Interweave content="This is <b>bold</b>." />`, which I could of sworn I had somewhere.

**Comment by milesj** [comment]
Pushed up some examples across the docs and readmes.
