### ISSUE TITLE
@babel/runtime

### ISSUE THREAD

**Issue by alonronin** [milesj/interweave#61]
Cannot use with webpack without `@babel/runtime` installed.

Consider Adding it as dependency to each of your packages as you described in your own package:
https://github.com/milesj/build-tool-config#install

**Comment by milesj** [comment]
@alonronin Whoops, nice catch. Switched to Babel last week and missed this!

**Comment by guycreate** [comment]
Is it possible to have `@babel/runtime` and the `@types/...` packages listed as devDependencies instead of dependencies?     I don't think they are needed when these packages are included as an npm module of another package and can create both version challenges as well as extra bloat.
