### ISSUE TITLE
Use custom whitelist

### ISSUE THREAD

**Issue by mindhaq** [milesj/interweave#62]
It's at least not clear from the documentation, or maybe even not possible - but how can I provide a custom whitelist of tags, and allow e.g. only `<b>` and `<i>` and remove everything else?

**Comment by milesj** [comment]
Interweave does not support a custom whitelist at this time.

**Comment by robertkraig** [comment]
@milesj I second this. I have content which also has `<em>` tags around content, and that content does not have the matcher applied to it. You're library is exceptional but I don't think it would be prudent to have a forked version as it's been so helpful in developing the product i'm working on.

**Comment by milesj** [comment]
You can possibly define a `transformer` for the time being. Might be a bit involved.

https://milesj.gitbook.io/interweave/parser#replacing-elements

**Comment by milesj** [comment]
@mindhaq @robertkraig Just tagged an alpha v11 that includes some new stuff to handle this: https://github.com/milesj/interweave/blob/master/packages/core/CHANGELOG.md#1100

**Comment by milesj** [comment]
Supported with `allowList` in v11.
