### ISSUE TITLE
newWindow=true should add rel="noopener noreferrer"

### ISSUE THREAD

**Issue by mindhaq** [milesj/interweave#63]
If links are are created with `newWindow={true}`, those links should als have the attribute `rel="noopener noreferrer"`.

See https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ for context.

If this can be done by customization already, I could not find it in the documentation.

**Comment by milesj** [comment]
That `rel` is applied to all links currently: https://github.com/milesj/interweave/blob/master/packages/autolink/src/Link.tsx#L25

**Comment by mindhaq** [comment]
Sorry, should have checked that before! For me, that would be enough, so I'll close that.
