### ISSUE TITLE
<em>{MyMatchString}</em> is never fed into the matchers

### ISSUE THREAD

**Issue by robertkraig** [milesj/interweave#64]
Not sure why, but any type of tags in this list: 

```
  'a',
  'abbr',
  'b',
  'br',
  'button',
  'canvas',
  'cite',
  'code',
  'del',
  'dfn',
  'em',
  'i',
  'iframe',
  'img',
  'ins',
  'kbd',
  'label',
  'mark',
  'output',
  'q',
  's',
  'samp',
  'script',
  'source',
  'span',
  'strong',
  'sub',
  'sup',
```

Is not being parsed by the matchers. But in div and some other tag types my content gets parsed. Trying to understand why.

**Comment by milesj** [comment]
Not all tags are allowed, some elements are blocked: https://github.com/milesj/interweave/blob/master/packages/core/src/constants.ts#L37

This is to prevent XSS/injection/etc.

**Comment by robertkraig** [comment]
I have a scenario where I'm replacing content sometimes inside of `em`, `strong`, `i`, `b` tags etc. and because they're formatting tags for text they seem to get skipped over. So long as something is not inside of these types of tags they work.

**Comment by milesj** [comment]
@robertkraig You have a full example? Updating interweave right now and want to get this in.

**Comment by milesj** [comment]
@robertkraig I figured out your issue. The parser checks that certain tags can be rendered within other tags here: https://github.com/milesj/interweave/blob/master/packages/core/src/Parser.ts#L197

And since `em` is marked as inline, it doesn't permit block elements, but it should allow other inline.

**Comment by milesj** [comment]
This should fix it: https://github.com/milesj/interweave/commit/62051e0e3a434613dd3fad498c7ca9ebbdf4b26c

Will be in the next alpha version.

**Comment by milesj** [comment]
Haven't explicitly tested this scenario, but give v11 a shot. Closing for now.
