### ISSUE TITLE
Provide full example for using Emoij component

### ISSUE THREAD

**Issue by gajus** [milesj/interweave#67]
Based on documentation, I have the following set up:

```js
import Interweave from 'interweave';
import withEmojiData, { EmojiMatcher } from 'interweave-emoji';

const LocalInterweave = withEmojiData({
  compact: false
})((props) => {
  const { emojis, emojiData, emojiSource, ...restProps } = props;

  return <Interweave
    
    {...restProps}
    emojiPath='https://github.com/twitter/twemoji/blob/gh-pages/36x36/{{hexcode}}.png'
    matchers={[
      new EmojiMatcher('emoji', {
        convertEmoticon: true,
        convertShortcode: true
      }),
    ]}
  />;
});

<LocalInterweave
    content="This will convert emoji unicode characters (🌀), shortcodes (:cyclone:), and emoticons to SVGs! :)"
 />

```

This gives an error:

> EmojiMatcher.js:163 Uncaught Error: Missing emoji source data. Have you loaded using `withEmojiData`?

Having read the docs, it is not clear what is the reason I am getting this error.

**Comment by milesj** [comment]
Why are you removing the props here? `const { emojis, emojiData, emojiSource, ...restProps } = props;`. I'm pretty sure they need to be passed down.

**Comment by gajus** [comment]
Thats how it is documented.

https://milesj.gitbook.io/interweave/extensions/emoji#loading-emoji-data

**Comment by milesj** [comment]
😱 Oh my, yeah that's my fault. 

@gajus  Did you verify it works when not removing them?

**Comment by gajus** [comment]
Yes, it does. I figured it out at the end, but other things were broken too (CSS examples). Ended up going with another library.

Thank you for taking a look.

**Comment by milesj** [comment]
@gajus Interweave doesn't provide CSS, so what exactly was the issue there?

**Comment by gajus** [comment]
* https://github.com/milesj/interweave/blob/master/tests/slack.css
* https://github.com/milesj/interweave/blob/master/tests/twitter.css

**Comment by milesj** [comment]
Interweave doesn't ship with its own CSS as every consumer will want to customize it differently. It even states that the Slack/Twitter CSS are purely a proof a concept, showcasing its customizability, and is more of a starting point.

> Slack and Twitter themes provided as an example of the library's robustness.
