### ISSUE TITLE
Update interweave to use emojibase 3

### ISSUE THREAD

**Issue by sapkra** [milesj/interweave#72]
I've installed emojibase in my repository (like it's documented) and used it with interweave but had some problems. It's a problem because it's not documented to explicitly install emojibase 2.2.0 (but yeah I saw it's definded as a peerDdependency).
The best way to fix everything would be to just update the project to 3.0.0.

- `Warning: Each child in a list should have a unique "key" prop.` in GroupTabs
- missing group in EmojiPicker

All this happens because some constants are `undefined` now.

btw. amazing work this library is really great

**Comment by milesj** [comment]
@sapkra Yeah interweave requires emojibase v2. Emojibase v3 uses the new emoji spec, which most, if not all OS's do not support yet.

**Comment by sapkra** [comment]
Ahh ok then we have to wait until the most OS's have support and maybe update the docs in the meanwhile.

**Comment by milesj** [comment]
Will land in v12.
