### ISSUE TITLE
Handle interleaved matchers

### ISSUE THREAD

**Issue by gcascio** [milesj/interweave#73]
I am facing issues when I interleave matchers. For a simple example I got a matcher for markdown like syntax which maps like this:

```javascript
/\*(.*?)\*/ => <strong>firstCapturingGroup</strong>
/\_(.*?)\_/ => <i>firstCapturingGroup</i>
```
This works as expected for simple contents like `*foo*` or `_foo_`.
The result for interleaved content like `_*foo*_` is `<i>#{{0}}#</i>` instead of the intended `<i><strong>foo</strong></i>`.

I understand why this happens but I couldn't think of a simple fix/workaround. Is there a recommended way to handle this case?

**Comment by milesj** [comment]
@gcascio Yeah, I'm not sure this is supported at the moment. I can dig into it a bit and maybe can rewrite the token phase.

**Comment by gcascio** [comment]
@milesj That would be great! Please let me now if you need any help or I can take over some work.

**Comment by milesj** [comment]
I looked into this briefly and it's much more complicated than I thought it would be. The way it works is as follows:

- First pass: Matchers are ran against a string. If a match is found, the match is replaced with a token. This continues till all matchers are complete.
- Second pass: The string is then converted into an array of React nodes, where each token is replaced with a React element. This array is the rendered.

It's very difficult to add interleaving to the first pass, as you've noticed. But it's also very difficult to run matchers against a string that is also being converted to an array at the same time. Not sure of a good solution at the moment.

**Comment by gcascio** [comment]
Thanks a lot for looking in to it! I also had a look at the code base and tried to come up with a solution, but as you already said it's quite a task. And even if the token phase would be enhanced to support interleaving, just interleaving the (random) React elements provided by the matchers is something what could cause trouble.

**Comment by sapkra** [comment]
@milesj Yesterday someone told me that a chat tool he is using has the problem that when you post source code the following string `;)` will be converted to an emoji. So it would be great if you can consider to prevent behaviors like this. Maybe with an option that some matchers cannot be interleaved.

**Comment by milesj** [comment]
@sapkra That's interesting since the regex matches against word boundaries. https://github.com/milesj/interweave/blob/master/packages/emoji/src/EmojiMatcher.ts#L19 Maybe something else is going on.

**Comment by sapkra** [comment]
This chat tool is not using your interweave library but I just wanted to notice it to prevent possible bugs in the future. No worries. 😉
Great that your library seems to already catch this case.

**Comment by milesj** [comment]
Attempting this here: https://github.com/milesj/interweave/pull/89 It's becoming quite difficult.

**Comment by milesj** [comment]
Got it working. Tagged `interweave@12.0.0-alpha.0` if you want to test it. There are examples in that PR.

**Comment by sapkra** [comment]
Interleaving works perfectly when separating the matchers. Appreciate your work!
