### ISSUE TITLE
Conditionally styled emoji

### ISSUE THREAD

**Issue by anri-asaturov** [milesj/interweave#8]
Hi, first of all, this is damn great work, respect, and i don't know why this repo doesn't have a millions stars yet.

Now to my question. Basically what I need to do is to render Slack-like jumboji, e.g. if chat message consists of a single emoji - render is larger. And ofc performance is important.

Right now I achieve that by detecting single emoji in `onAfterParse` and re-rendering message component. This is not ideal so I am thinking of ways to implement it in PR so that you would consider it useful and accept it. 

Thoughts?

**Comment by milesj** [comment]
Thanks for the kind words!

I'm actually working on v2 of the library right this moment. I can quickly look into this.

**Comment by milesj** [comment]
Got it working. 
<img width="203" alt="screen shot 2016-12-12 at 23 08 30" src="https://cloud.githubusercontent.com/assets/143744/21130835/dbf97fce-c0bf-11e6-87f3-93f25a0f0529.png">

**Comment by milesj** [comment]
Done! Thanks for the awesome idea.

**Comment by anri-asaturov** [comment]
Oh. Thanks. Those callbacks will definitely be useful. Are you working on this as a part of some project?

**Comment by milesj** [comment]
@anri-asaturov We use this a bit at my work, but besides that, mainly for fun. Wanted to learn more about emojis.

**Comment by anri-asaturov** [comment]
Quick question, if you don't mind - how do u publish npm package so `/lib` becomes a root?

**Comment by milesj** [comment]
Just append the folder to the publish command: `npm publish ./lib/`. Which I seem to forgot to do a lot, like I did with the 2.0.0 release. Had to bump a 2.0.1.

I'm also working on a new release/deploy tool that builds and stages everything to lib/, then deploys it as root.

**Comment by anri-asaturov** [comment]
Thanks. Btw, emoji enlargement doesn't work if convertEmoji=false, I'll try to fix that soon.

**Comment by milesj** [comment]
It'll only work if the `Emoji` component is rendered. Unicode emojis will be rendered as is.

**Comment by anri-asaturov** [comment]
We could wrap them in a `span` if they have to be enlarged. Or apply the enlargement class to parent node?

**Comment by milesj** [comment]
That may work. We would just need a way to cleanly verify that a span + unicode symbol is an emoji React element.

**Comment by anri-asaturov** [comment]
What if we just modify the same Emoji component to render unicode if that's the setting?

**Comment by milesj** [comment]
Yeah most likely. We can move this logic to a prop on the `Emoji` component. 

https://github.com/milesj/interweave/blob/master/src/matchers/Emoji.js#L29

```
<Emoji {...props} renderUnicode={this.options.renderUnicode} />
```
