### ISSUE TITLE
package 'interweave-ssr' not found

### ISSUE THREAD

**Issue by wouterds** [milesj/interweave#87]
How does one use SSR? I'm trying to implement this and in the docs it says install `interweave-ssr` but that [package does not exist on npm.js](https://www.npmjs.com/package/interweave-ssr)?

**Comment by wouterds** [comment]
Ah, just saw this https://github.com/milesj/interweave/issues/80#issuecomment-532779038.

**Comment by milesj** [comment]
Yeah sorry, hasn't been released yet. Will be released in a few weeks hopefully.

**Comment by wouterds** [comment]
Couldn't get SSR to work with JSDOM (in a Next.js project). Not sure where to call it, tried a couple of different places but doesn't seem to affect anything. But off-topic for this issue.
