### ISSUE TITLE
oembed tag

### ISSUE THREAD

**Issue by zehawki** [milesj/interweave#98]
Hi Miles, what do you feel about allowing oembed tag out of the box? If I'm not wrong, Markup currently strips it out, though its not mentioned anywhere in the documentation.

Conversely: can I add only this in allowList prop, or will I have to then mention ALL the existing tags that you've defined in ALLOWED_TAG_LIST + "oembed" in order to keep things working?

BTW: using Interweave everywhere on nextelection.com successfully for a year :-)

**Comment by zehawki** [comment]
Maybe I have it ass-backwards. Prolly I need to handle oembed _before_ sending it to Markup for rendering.

**Comment by milesj** [comment]
@zehawki Yeah, I have no idea what `oembed` is. This sounds like something non-standard so is definitely not supported in core.

**Comment by zehawki** [comment]
Quite a useful thingy, btw: https://oeambed.com
I came across it since I integrated CKeditor today and they use it.

**Comment by milesj** [comment]
Custom elements should be handled with a custom implementation.
